### ISSUE TITLE
HTML Snippet Formatting with Weird Breaks

### ISSUE THREAD

**Issue by alexlafroscia** [whitespace-se/storybook-addon-html#10]
I'm seeing some weird results in the formatting of the HTML snippets that I get from this addon (which is excellent, by the way!)

I have some input HTML that looks like this:

```html
<div class="fluid-button-group">
  <button class="fluid-button">Left Button</button>
  <button class="fluid-button">Middle Button</button>
  <button class="fluid-button">Right Button</button>
</div>
```

But when it's formatted in the addon panel, it ends up looking like this

```html
<div class="fluid-button-group">
  <button class="fluid-button">Left Button</button
  ><button class="fluid-button">Middle Button</button
  ><button class="fluid-button">Right Button</button>
</div>
```

I'm not sure why the `>` of those closing HTML tags ends up on the next line, but it does!

One thought I had was that it is likely an issue with Prettier. Would you be open to a PR that upgrades this package to make use of Prettier 2.0? That might be a good way to ensure that possible issues with Prettier itself are resolved in the formatter as it is used here.

**Comment by hyunchulkwak** [comment]
I had the same result from the version 1.2.1. Setting prettier config `htmlWhitespaceSensitivity` to `ignore` worked for me. This is my config, FYI.

```
addDecorator(withHTML({
  prettier: {
    tabWidth: 2,
    useTabs: false,
    printWidth: 140,
    htmlWhitespaceSensitivity: 'ignore'
  },
}));
```

**Comment by alexlafroscia** [comment]
Good tip @hyunchulkwak -- I'll try that out!

**Comment by jeanfredrik** [comment]
The default value for Prettier’s `htmlWhitespaceSensitivity` is `css`, which tries to preserve whitespace between inline elements, like `<button>` in your example. This is to prevent extra spaces showing up between inline elements. Since the purpose if this formatting is different, it would make more sense to have it set to `ignore` by default. This is fixed in 1.2.4.

**Comment by jeanfredrik** [comment]
I have also upgraded Prettier to 2.x

**Comment by alexlafroscia** [comment]
Awesome! Thanks @jeanfredrik 😁 Looking forward to a release with the fix!

**Comment by jeanfredrik** [comment]
Try updating to 1.2.4

**Comment by alexlafroscia** [comment]
Looks _so_ much better now! Perfect. Thanks @jeanfredrik!
