### ISSUE TITLE
ValidationError: Invalid configuration object when using the addon in Storybook v7

### ISSUE THREAD

**Issue by MichaelRydl** [whitespace-se/storybook-addon-html#102]
Hello,

I have a problem with the "@whitespace/storybook-addon-html" when I´m using it in Storybook v7.

When I try to build and run Storybook I get this error:
![image](https://github.com/whitespace-se/storybook-addon-html/assets/29844074/69d492fc-509a-4900-81a6-265cdefcdc7e)

When I comment out the addon from the "main.js" file, then it works fine and I´m able to build and run Storybook.

Do you have any idea why is this happening?

**My version of this addon is: "~5.1.6", version of the Webpack is "^5.86.0" and version of the Storybook is "^7.0.20".**

This is my "main.js" file:
![image](https://github.com/whitespace-se/storybook-addon-html/assets/29844074/287c4ec8-6682-40c4-93a4-a4a0df153ce9)

Thank you.

**Comment by AlexSkrypnyk** [comment]
The same issue with SB 6

**Comment by tfrijsewijk** [comment]
```
WARN You (or an addon) are using the 'config' preset field. This has been replaced by 'previewAnnotations' and will be removed in 8.0
```

The error gave it away. If I remove the `module.exports.config` property from `preset.js` everything works. It appears as if Storybook is evaluating both `config` and `configAnnotations`. Addons should pick one. Starting from SB8 `config` will not be used anymore.

**Comment by stubar** [comment]
I am also facing this issue,  the patch didn't seem to work for me.  Although I've not actually used `[patch-package](https://github.com/ds300/patch-package)` I just went in and edited preset.js manually.

I'm on SB 6 with @whitespace/storybook-addon-html@5.1.6

**Comment by tfrijsewijk** [comment]
> I am also facing this issue, the patch didn't seem to work for me. Although I've not actually used `[patch-package](https://github.com/ds300/patch-package)` I just went in and edited preset.js manually.
> 
> I'm on SB 6 with @whitespace/storybook-addon-html@5.1.6

Make sure to delete the Storybook build cache directory before testing changes in node_modules. I believe it's located in `/node_modules/.cache`.
