### ISSUE TITLE
Storybook 7 HTML addon showing error

### ISSUE THREAD

**Issue by sayedbs** [whitespace-se/storybook-addon-html#107]
# Storybook 7 Html Addon not working it's showing error.

![error screensot from browser](https://ebrevial.sirv.com/Addon%20HTMl%20Storybook/image%2010.jpg)

this error show when I installed HTML addon in my storybook app. 
my configuration is:

**min.js**
```
    const config ={
    	...,
    	addons[...,"@whitespace/storybook-addon-html"]
    }
```
 
**preview.js**
```
    const  preview  = {
    	parameters: {
         html: {
        		prettier: {
    	    		tabWidth:  4,
    	    		useTabs:  false,
    	    		htmlWhitespaceSensitivity:  "strict",
    	    	},
    },
```
Then showing error here:
![image 1](https://ebrevial.sirv.com/Addon%20HTMl%20Storybook/1.jpg)
![error image 2](https://ebrevial.sirv.com/Addon%20HTMl%20Storybook/2.jpg)

how can I solve it any idea or example solutions plz.
Thanks, Advance

**Comment by 42tte** [comment]
Duplicates #104
