### ISSUE TITLE
Prettier 3 support

### ISSUE THREAD

**Issue by Ollitod** [whitespace-se/storybook-addon-html#110]
The package has a peerDependency to **"prettier": "^2.0.0"**.
In our Angular project (v17) we are using Prettier in version 3.1 to take advantage of formatting rules for Angular's new control flow syntax, which was introduced in version 17 back in November.
The peerDependency version of the package leads to dependency resolution conflicts in our Angular project at the moment.
Please update to **"prettier": "^3.0.0"**.

Thanks a lot!

**Comment by jeanfredrik** [comment]
We just released version 6.0.0 which uses Storybook 8 and Prettier 3. Please try to update to the latest version and see if everything works.
