### ISSUE TITLE
TypeError: Cannot read property 'innerHTML' of null when update snapshots of storybook

### ISSUE THREAD

**Issue by nguyenvantruong17** [whitespace-se/storybook-addon-html#17]
![TypeError](https://user-images.githubusercontent.com/18642063/88618600-b6a9c180-d0c3-11ea-8d5e-266733b80d23.png)

I got some error when update snapshots. Anybody knows what is it?
This is my config
- addDecorator(withHTML()) on `config.js`
- import '@whitespace/storybook-addon-html/register' on `addons.js`

**Comment by jeanfredrik** [comment]
Duplicate of #5
