### ISSUE TITLE
Add support for more frameworks

### ISSUE THREAD

**Issue by jeanfredrik** [whitespace-se/storybook-addon-html#2]
Storybook supports these frameworks and we need to provide a decorator for each of them:
- [x] HTML
- [x] React
- [ ] React Native
- [ ] Vue
- [ ] Angular
- [ ] Mithril
- [ ] Marko
- [ ] Ember
- [ ] Riot
- [ ] Svelte

**Comment by tim-thaler** [comment]
Here is somthing I created for VueJS but with a dependency to @vue/test-utils.
Is there a better way?

`import { addons, makeDecorator } from '@storybook/addons';
import { EVENT_CODE_RECEIVED } from '@whitespace/storybook-addon-html/lib/shared';
import { mount } from '@vue/test-utils';
 
export const withHTML = makeDecorator({
  name: 'withHTML',
  parameterName: 'html',
  skipIfNoParametersOrOptions: false,
  wrapper: (getStory, context, {options = {}}) => {
    const channel = addons.getChannel();
    const wrapper = mount(getStory());
    channel.emit(EVENT_CODE_RECEIVED, {html: wrapper.html(), options});
    return getStory();
  },
});`

**Comment by ChazUK** [comment]
Is there any timeline adding Angular to this package?

**Comment by jeanfredrik** [comment]
@tim-thaler Looks good! Would you be able to create a pull request and we could continue from there?

**Comment by jeanfredrik** [comment]
Any help with adding support for Angular would be much appreciated.

**Comment by jeanfredrik** [comment]
Version 4.0.0 adds support for all frameworks since custom code for each framework is no longer necessary.
