### ISSUE TITLE
showLineNumbers disabled

### ISSUE THREAD

**Issue by nijk** [whitespace-se/storybook-addon-html#21]
Hi, this addon is really helpful - thank you for sharing it 👍 

I've noticed that [`showLineNumbers` is set to `false`](https://github.com/whitespace-se/storybook-addon-html/blob/master/src/SyntaxHighlighter.js#L105). Would you consider allowing this prop to be configurable?

**Comment by jeanfredrik** [comment]
There’s a parameter for this now in version 4.2.0. Check the Readme
