### ISSUE TITLE
Update html compiled code when props are changed using knobs

### ISSUE THREAD

**Issue by JonnyPS** [whitespace-se/storybook-addon-html#3]
I have successfully installed the html addon to my storybook project.
I am also using the knobs addon, I expected the compiled html code to update when I changed the value of the knobs, is it supposed to or is this not a feature?

Thank you

**Comment by jeanfredrik** [comment]
Hi JonnyPS,
Let me take a look at this to make sure that this addon works with Knobs.

**Comment by jeanfredrik** [comment]
This should be fixed in v1.2.0 now.
