### ISSUE TITLE
storybook has a root-inner wrapper

### ISSUE THREAD

**Issue by dutscher** [whitespace-se/storybook-addon-html#35]
Storybook 6.1.10 renders a: `<div id="root-inner">` which is unecessary.

![image](https://user-images.githubusercontent.com/14682/103624164-70417400-4f39-11eb-9dfe-9e5d9da82a53.png)
![image](https://user-images.githubusercontent.com/14682/103624211-818a8080-4f39-11eb-903d-4b84555e2f45.png)

the selector is hardcoded: https://github.com/whitespace-se/storybook-addon-html/blob/master/addon/src/decorators/withHTML.js#L11

is it possible to configure the preview selector?

cheers

**Comment by jeanfredrik** [comment]
Thanks for reporting this. It’s now fixed in version 4.1.0
