### ISSUE TITLE
Feature Request: Define custom root node

### ISSUE THREAD

**Issue by savgrace** [whitespace-se/storybook-addon-html#36]
Within the **withHTML.js** decorator, instead of selecting #root, what do you guys think of allowing this root element to be selected via a parameter?  
I can create a Pull Request if need be. 
I'm asking because in our project we're using Svelte with the **Component**View.svelte pattern (as recommended in the Storybook docs) in order to render things in preview that aren't part of the **Component** itself. For example, rendering a grid of icons. This means the plugin spits out all the HTML from **Component**View.svelte instead of just Component.svelte.

Thanks

**Comment by dutscher** [comment]
this is the same in this issue :D https://github.com/whitespace-se/storybook-addon-html/issues/35

cheers and +1
