### ISSUE TITLE
Addon breaks with Storybook upgrade to 5.3.3

### ISSUE THREAD

**Issue by JonnyPS** [whitespace-se/storybook-addon-html#4]
Hello,

I have upgraded storybook to 5.3.3 and this addon is not working anymore.

I see that HTML tab on the addons panel, but nothing displays.

Below is a section of my package.json file:
```
"devDependencies": {
    "@babel/core": "^7.7.7",
    "@storybook/addon-a11y": "^5.3.3",
    "@storybook/addon-actions": "^5.3.3",
    "@storybook/addon-docs": "^5.3.3",
    "@storybook/addon-info": "^5.3.3",
    "@storybook/addon-knobs": "^5.3.3",
    "@storybook/addon-links": "^5.3.3",
    "@storybook/addon-viewport": "^5.3.3",
    "@storybook/addons": "^5.3.3",
    "@storybook/preset-create-react-app": "^1.5.1",
    "@storybook/react": "^5.3.3",
    "@whitespace/storybook-addon-html": "^1.2.0",
    "babel-loader": "^8.0.6",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^3.4.1",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "file-system": "^2.2.2",
    "html-webpack-plugin": "^3.2.0",
    "jest": "^24.9.0",
    "jest-cli": "^24.9.0",
    "mini-css-extract-plugin": "^0.9.0",
    "node-sass": "^4.13.0",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "pa11y": "^5.3.0",
    "prop-types": "^15.7.2",
    "remove-files-webpack-plugin": "^1.2.1",
    "sass": "^1.24.2",
    "sass-loader": "^8.0.0",
    "style-loader": "^1.1.2",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "webpack": "^4.41.5",
    "webpack-cli": "^3.3.9",
    "webpack-merge": "^4.2.2"
  }
```

main.js:
```
module.exports = {
  stories: ['../src/**/*.stories.js'],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-actions',
    '@storybook/addon-links',
    '@storybook/addons',
    '@storybook/addon-a11y',
    '@storybook/addon-docs/register', // still need to add /register with sb updgrade 5.3.3
    '@storybook/addon-knobs/register', // still need to add /register with sb updgrade 5.3.3
    '@storybook/addon-viewport',
    '@whitespace/storybook-addon-html/register',
  ],
};
```
manager.js
```
import { withHTML } from '@whitespace/storybook-addon-html/react';
addDecorator(withHTML);
```

**Comment by jeanfredrik** [comment]
Hi JonnyPS,
I will look into it. What’s the highest version of Storybook that it does work on for you?

**Comment by JonnyPS** [comment]
Thank you, - I was using it fine on 5.2.8, upgrade to 5.3.3 is what broke it.

________________________________

**Comment by jeanfredrik** [comment]
I have tested the addon with Storybook 5.3 and all is working like before. Can you try moving the `addDecorator` part to _.storybook/preview.js_?

Check out https://github.com/whitespace-se/storybook-addon-html/tree/master/examples for working example using React with 5.3.

**Comment by JonnyPS** [comment]
HI @jeanfredrik - Thanks for looking into this.... I have already got the addDecorator in the preview.js file.... I had a look at the example in the React folder, but unless i'm missing something, the package.json file doesn't include any react scripts....

**Comment by JonnyPS** [comment]
PS - I tried updating devDependencies to match the package.json example package.json in the react folder but still nothing....

**Comment by JonnyPS** [comment]
Update - I have created a new sample project using sb5.3.4, with react, and added the html addon.
It seems to be working correctly, so there is something in my project stopping it, let me look into it.

**Comment by JonnyPS** [comment]
I have completely re init my project and added all dependencies one by one, i don't know what was the original cause of the issue but everything seems to be working fine now....

**Comment by jeanfredrik** [comment]
No worries. I’m glad you solved it!
