### ISSUE TITLE
Bug report: storybook@6.1.21 is incompatible with this add on

### ISSUE THREAD

**Issue by artmsilva** [whitespace-se/storybook-addon-html#42]
I recently upgraded to storybook@6.1.21. This add on @4.2.0 is throwing this error.

> Uncaught TypeError: Cannot read property 'name' of undefined

**Comment by tommybl** [comment]
I recently upgraded to `6.1.21` from `6.0.20` and I now get this error regarding Prettier:

```
ERROR in ./node_modules/@whitespace/storybook-addon-html/node_modules/prettier/standalone.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find intersection at NodePath.getDeepestCommonAncestorFrom
```

**Comment by jeanfredrik** [comment]
This should now be fixed in the latest major version. I’ve updated all deps and that seemed to do it for the example apps in the repo. Please report back if upgrading to ^5.0.0 doesn’t solve the problem for you.

**Comment by tommybl** [comment]
Hi @jeanfredrik,

Unfortunately I still get the same error after upgrading storybook to 6.1.21 from 6.0.20, and upgrading storybook-addon-html to 5.0.0:

```
ERROR in ./node_modules/@whitespace/storybook-addon-html/node_modules/prettier/standalone.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find intersection at NodePath.getDeepestCommonAncestorFrom
```

I have babel-loader `^8.1.0`

Thanks

**Comment by jeanfredrik** [comment]
It might be a separate bug then. Would you mind opening a new issue for it?

**Comment by tommybl** [comment]
Thanks @jeanfredrik, I opened a new issue there:

https://github.com/whitespace-se/storybook-addon-html/issues/45
