### ISSUE TITLE
Incompatibility with storybook@6.1.21

### ISSUE THREAD

**Issue by tommybl** [whitespace-se/storybook-addon-html#45]
I recently upgraded storybook to `6.1.21` from `6.0.20`, and this storybook-addon-html addon to the latest `5.0.0`, I get this error:

```
ERROR in ./node_modules/@whitespace/storybook-addon-html/node_modules/prettier/standalone.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find intersection at NodePath.getDeepestCommonAncestorFrom
```

I have babel-loader `^8.1.0`.

Thanks

**Comment by BigFly3** [comment]
I'm using this add-on @ 2.0.1 and it's working up to @ 6.1.20.
After updating to @ 6.1.21, it stopped working.
I also tried @ 6.2.3 but it doesn't seem to work continuously.

**Comment by jeanfredrik** [comment]
I’m not sure how to fix this. I’m continuing my digging into the matter, but meanwhile I’ve also reached out to the Storybook team in this issue: https://github.com/storybookjs/storybook/issues/14489

I hope we can find a solution soon!

**Comment by shilman** [comment]
Looks like there's a workaround here:

https://github.com/babel/minify/issues/904#issuecomment-424367995

Can you try overriding your babel settings to include these? You can look at Storybook's babel settings by running `yarn storybook --debug-webpack` and looking at the `babel-loader` entry in Preview. Or you can just override the `babel` setting in `.storybook/main.js`

https://storybook.js.org/docs/react/addons/writing-presets#babel

**Comment by denniscohn** [comment]
Any progress on this?
I've tried the workaround, but I'm not that technical... so I now disabled the storybook-addon-html but hoping for a solution on a shirt term. 
Or if anyone can tell me, what I need to change so the storybook-addon-html will work again... that's also great!

**Comment by jeanfredrik** [comment]
I’m taking another look now

**Comment by jeanfredrik** [comment]
I need more info on how to reproduce this.

@tommybl Can you provide your config, i.e. package.json, .storybook/main.js and .storybook/preview.js or a complete repo?

**Comment by denniscohn** [comment]
For me, it's no longer an issue anymore.
I've deleted my node_module folder and run the update again, maybe I also did a npm install.
Somehow, it works now...

**Comment by jeanfredrik** [comment]
Ok, great! I guess this is mostly caused by mismatches between versions of Babel, Webpack and other dependencies. I’ll close this for now.
