### ISSUE TITLE
CSS is being minified on build-storybook

### ISSUE THREAD

**Issue by calebsmithdev** [whitespace-se/storybook-addon-html#58]
Hey there! I've been battling with this for a bit and I am stumped on how to move forward. When we are running the storybook in development, all of our code looks great in the HTML addon and looks as clean as we want it. On `build-storybook`, the CSS is shrunk down to one line and we have no control of it. This only seems to be impacting the CSS. Example:

![Screen Shot 2021-10-25 at 3 49 03 PM](https://user-images.githubusercontent.com/3040113/138768715-239123db-5aec-4300-8378-db058cddc8b9.png)

Any tips on how we can configure the addon to show the CSS whitespace?

**Comment by jeanfredrik** [comment]
Hi @calebsmithdev! Were you able to resolve this?

**Comment by calebsmithdev** [comment]
Hey! We decided it was an acceptable problem and just made it clear to the team to format the CSS separately on their own, as needed.

**Comment by jeanfredrik** [comment]
Let me know if you have the same issue after upgrading to version 5 of the addon. I'll close this for now.
