### ISSUE TITLE
Compiled HTML not updating in line with React component 

### ISSUE THREAD

**Issue by JonnyPS** [whitespace-se/storybook-addon-html#6]
I am using Storybook 5.3.7 with html addon 1.2.1

I am also using knob addon to update the props of the React component.

When I update the props - in this case it adds or remove classes names from targeted DOM elements, I see that when I inspect the html in the console, the classes have been added/removed as expected, but the compiled html has not updated in the addon.
 It does update however, if i then update props for a second time - essentially the compiled html is once step behind compared to what's actually going on in the dom.

I am updating the props on my component using the componentDidUpdate() 

Thank you, let me know if you need any more information.

**Comment by jeanfredrik** [comment]
Hi @JonnyPS ,
Did you figure this out on your own? Otherwise, if it’s still relevant for you, can you provide a code example?

**Comment by jeanfredrik** [comment]
I’m closing this now. Feel free to re-open if this is still a relevant issue.
