### ISSUE TITLE
How to remove Lit HTML comments?

### ISSUE THREAD

**Issue by yannickoo** [whitespace-se/storybook-addon-html#64]
When working with [Lit](https://lit.dev) components you will find HTML code like this ⬇️ 

```
<my-button>
  <!--?lit$7082895866$-->
  <!--?lit$7082895866$-->Primary Button
  <!--?lit$7082895866$-->
</my-button>
```

How should we support a way to remove those comments [here](https://github.com/whitespace-se/storybook-addon-html/blob/master/addon/src/decorators/withHTML.js#L15)?

Thanks 🤗

**Comment by heihong** [comment]
i have the same problem
this regex /g, not work
<img width="934" alt="regex" src="https://user-images.githubusercontent.com/4026061/149965144-00403c3e-0f4b-4e0f-8781-c9c04c9036bb.PNG">

**Comment by yannickoo** [comment]
Maybe we could [this](https://regex101.com/r/FzTNh3/1) regex to get rid of every HTML comment no matter what's inside?

<img width="687" alt="Screenshot 2022-01-19 at 00 58 26" src="https://user-images.githubusercontent.com/1086961/150038016-0a0f9b08-e815-4c28-be09-ea012fea4970.png">

**Comment by jeanfredrik** [comment]
I think a regex or filter callback is the way to go. Me and the other developers at Whitespace are planning to do some maintenance (go through issues and merge PRs) this and next week. Thank you for your patience!

**Comment by jeanfredrik** [comment]
It's now possible to define what comments to remove with the `removeComments` parameter and providing a regular expression. I hope it solves this issue for you!
