### ISSUE TITLE
Vue3 and Vite support?

### ISSUE THREAD

**Issue by kasperskov909** [whitespace-se/storybook-addon-html#68]
Are Vue3 and Vite build supported? I've done some initial tests and can't get it to work.
Before I dig any deeper I need to get a clarification if Vue3 and Vite are even supported?

**Comment by aboutsimon** [comment]
There is already another issue for vite support open https://github.com/whitespace-se/storybook-addon-html/issues/59

**Comment by jeanfredrik** [comment]
Thanks for noticing this. Me and the other developers at Whitespace are planning to do some maintenance (go through issues and merge PRs) this and next week. Thank you for your patience!

**Comment by jeanfredrik** [comment]
Version 5 of the addon should work with Vue3 and Vite. Let me know if it doesn't. I'll close this for now.

**Comment by kasperskov909** [comment]
FYI @jeanfredrik Version 7 of Storybook breaks the plugin.. Thought you should know.

**Comment by jeanfredrik** [comment]
If the Storybook 7.0 compatibility issue is related to #94 that is fixed in v5.1.4. If not, please open a separate issue or PR.
