### ISSUE TITLE
Peer dependency incompatibility with storybook v7

### ISSUE THREAD

**Issue by sovanyio** [whitespace-se/storybook-addon-html#96]
Haven't extensively tested it in v7, but fixing the peer dep locally with `|| ^7.0.0` and updating the preset.js as follows works to get a working HTML tab:

```
function previewAnnotations(entry =[]) {
  return [...entry, require.resolve("./dist/esm/preset/preview")];
}

function managerEntries(entry = []) {
  return [...entry, require.resolve("./dist/esm/preset/manager")];
}

module.exports = {
  managerEntries,
  previewAnnotations,
};
```

**Comment by robg-makemusic** [comment]
Please fix this, we can't update to Storybook 7 because of this

**Comment by volnei** [comment]
Same here!!!

**Comment by jeanfredrik** [comment]
#97 has been merged now. Let me know if you have any further issues. Sorry for keeping you waiting.
